baseURL = 'http://mbt925.github.io/'
languageCode = 'en-us'
title = 'Mohsen Biglari'
theme = "LoveIt"
themesDir = "themes"

[params]
  # LoveIt theme version
  version = "0.2.X"
  # site description
  description = "Mohsen Biglari's personal website"
  # site keywords
  keywords = ["Mohsen", "Biglari", "mbt925"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # Footer config
  [params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = false
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2022
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = 'Mohsen Biglari'

  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/logotrans.png"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Mobile Software Engineer  |  AI Engineer"
      # subtitle shown in home page
      subtitle = ""
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
  
  # Social config about the author
  [params.social]
    Email = "mbt925 at gmail dot com"
    GitHub = "mbt925"
    Linkedin = "mbt925"
    Twitter = "mbt9252"
    Telegram = "mbt925"

[menu]
  [[menu.main]]
    identifier = "Academia"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Academia"
    url = "/academia/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "Projects"
    pre = ""
    post = ""
    name = "Projects"
    url = "/projects/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "About"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 3